{% set name = "dash-core-components" %}
{% set filename = "dash_core_components" %}
{% set version = "1.13.0" %}
{% set sha256 = "f92025b12931539cdda2173f2b4cd077119cbabbf3ddf62333f6302fd0d8a3ac" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ filename }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - python ==2.7|>=3.3
    - setuptools
    - pip
  run:
    - python ==2.7|>=3.3
    - dash  # not listed in the setup.py

test:
  imports:
    - dash_core_components

about:
  home: https://plot.ly/dash
  dev_url: https://github.com/plotly/dash-core-components
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Dash UI core component suite

extra:
  recipe-maintainers:
    - moorepants
