{% set name = "dash-core-components" %}
{% set filename = "dash_core_components" %}
{% set version = "1.8.0" %}
{% set sha256 = "6ed00e421e4ff5ebe1bb91b0add168ef89cf2afbdff1e0cef91633dd338569c8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ filename }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - dash  # not listed in the setup.py

test:
  imports:
    - dash_core_components

about:
  home: https://plot.ly/dash
  dev_url: https://github.com/plotly/dash-core-components
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Dash UI core component suite'

extra:
  recipe-maintainers:
    - moorepants
